iotedge-{cli,daemon}: drop CARGO_SRC_DIR for compatibility with latest meta-rust
* CARGO_SRC_DIR is now used in MANIFEST_PATH after meta-rust commit:
  commit 4e960136779edb39685b018a0bfc023402e22d72
  Author: Benjamin Isbarn <benjamin.isbarn@gmail.com>
  Date:   Mon Feb 15 14:36:46 2021 +0100

    Factor in `CARGO_SRC_DIR` when setting `MANIFEST_PATH`.

  which changed the default
  MANIFEST_PATH ??= "${S}/Cargo.toml"

  to
  CARGO_SRC_DIR ??= ""
  MANIFEST_PATH ??= "${S}/${CARGO_SRC_DIR}/Cargo.toml"

  and iotedge-{cli,daemon} is now failing with:
  NOTE: cargo build -v --target aarch64-oe-linux --release --manifest-path=iotedge-cli/1.0.9.4-r0/iotedge-1.0.9.4/edgelet/iotedge/iotedge/Cargo.toml
  error: manifest path `iotedge-cli/1.0.9.4-r0/iotedge-1.0.9.4/edgelet/iotedge/iotedge/Cargo.toml` does not exist

diff --git a/classes/cargo.bbclass b/classes/cargo.bbclass
index 72e77b0..c2eee10 100644
--- a/classes/cargo.bbclass
+++ b/classes/cargo.bbclass
@@ -22,8 +22,12 @@ B = "${WORKDIR}/build"
 # where the issue occured
 export RUST_BACKTRACE = "1"

-# Assume there's a Cargo.toml directly in the source directory
-MANIFEST_PATH ??= "${S}/Cargo.toml"
+# The directory of the Cargo.toml relative to the root directory, per default
+# assume there's a Cargo.toml directly in the root directory
+CARGO_SRC_DIR ??= ""
+
+# The actual path to the Cargo.toml
+MANIFEST_PATH ??= "${S}/${CARGO_SRC_DIR}/Cargo.toml"

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>