containerize.sh: switch from cardoe/yocto to crops/poky
* cardoe/yocto wasn't updated in last 3 years and the gcc included in this image
  is too old for gatesgarth OE release as shown in:
  https://iotedge.visualstudio.com/iotedge/_build/results?buildId=50386&view=logs&j=2300b2b4-4206-5c4f-16ca-41bcbb8288aa&t=03c45bbf-90ac-5137-e381-689c3f1fcab4
  ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Your version of gcc is older than 6.0 and will break builds. Please install a newer version of gcc (you could use the project's buildtools-extended-tarball or use scripts/install-buildtools).

  switch to officially supported crops/poky image based
  on latest LTS Ubuntu release 20.04

Signed-off-by: Martin Jansa <martin.jansa@lge.com>